import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexClientProvider";
import { Toaster } from "sonner"; 
import TripDetailProvider from "@/context/TripDetailContext";

 // Adjust the path

const outfit = Outfit({
  subsets: ["latin"],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${outfit.className} `}
      >
        <ConvexClientProvider>
          {/* <Provider>
           
          </Provider> */}
           <TripDetailProvider>
              {children}
           <Toaster richColors position="top-right" />
             </TripDetailProvider>
        
        </ConvexClientProvider>
        
      </body>
    </html>
    </ClerkProvider>
  );
}
